# Generated by Django 4.0.6 on 2022-07-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_comment_is_active_products_gender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductCategory',
        ),
    ]
