# Generated by Django 4.0.6 on 2022-08-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_old_price_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(null=True, verbose_name='Цена без скидки'),
        ),
    ]
