# Generated by Django 4.0.6 on 2022-08-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена без скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
    ]
