# Generated by Django 4.0.6 on 2022-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='test_music',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
