# Generated by Django 4.0.6 on 2022-08-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
