# Generated by Django 4.0.6 on 2022-08-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_sizes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
