# Generated by Django 4.0.6 on 2022-08-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыка'},
        ),
    ]
