# Generated by Django 4.0.6 on 2022-08-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='track',
            field=models.TextField(),
        ),
    ]
