# Generated by Django 4.0.6 on 2022-08-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
