# Generated by Django 4.0.6 on 2022-08-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_video_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
