# Generated by Django 4.0.6 on 2022-08-04 12:50

from django.db import migrations, models
import phonenumber_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('city', models.TextField(verbose_name='Город доставки')),
                ('country', models.TextField(verbose_name='Страна доставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
    ]
