# Generated by Django 4.0.6 on 2022-08-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_order_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
