# Generated by Django 4.0.6 on 2022-08-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='postcode',
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
