# Generated by Django 4.0.6 on 2022-08-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
