# Generated by Django 4.0.6 on 2022-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_orderitem_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
